"""
Chat Pydantic schemas — designed for frontend consumption.

Design decisions:
  - is_ai: computed field on every message so the frontend does zero logic
    to distinguish AI vs human. No more checking sender_role AND sender_id.
  - ticket_id removed from MessageResponse: it is in the URL already; repeating
    it on every message in a list is pure noise. Kept in Firebase payloads only.
  - items -> messages: field name matches what it actually is.
  - has_more: explicit boolean. Frontend should not have to do
    `next_cursor !== null` to decide whether to show a "load more" button.
  - ThreadResponse: the "open chat window" payload. One HTTP call returns
    ticket context + first page of messages, eliminating two sequential requests.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import datetime

import bleach
from pydantic import BaseModel, ConfigDict, computed_field, field_validator

# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------


class SendMessageRequest(BaseModel):
    content: str

    @field_validator("content")
    @classmethod
    def sanitise_and_validate_content(cls, value: str) -> str:
        cleaned = bleach.clean(value, tags=[], attributes={}, strip=True).strip()
        if not cleaned:
            raise ValueError("Message content must not be empty.")
        if len(cleaned) > 2000:
            raise ValueError("Message content must not exceed 2000 characters.")
        return cleaned


# ---------------------------------------------------------------------------
# Message
# ---------------------------------------------------------------------------


class MessageResponse(BaseModel):
    """
    A single chat message.

    is_ai is computed server-side so the frontend renders with one flag,
    not two separate field checks. sender_id is still present for
    "is this my own message?" optimistic-UI detection.
    """

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    sender_id: uuid.UUID | None  # None for AI messages
    sender_role: str  # "user" | "superadmin" | "admin" | "assistant"
    content: str
    created_at: datetime

    @computed_field  # type: ignore[misc]
    @property
    def is_ai(self) -> bool:
        """True when this message was generated by the AI assistant."""
        return self.sender_role == "assistant"


# ---------------------------------------------------------------------------
# Paginated message list  (GET /{ticket_id}/messages)
# ---------------------------------------------------------------------------


class MessageListResponse(BaseModel):
    """
    Cursor-paginated list of messages.

    Pagination flow:
      1. Initial:   GET /{ticket_id}/messages?limit=50
         -> messages = latest 50 oldest-first, next_cursor = id of oldest
      2. Load more: GET /{ticket_id}/messages?before_id=<next_cursor>&limit=50
      3. has_more=false -> beginning of thread reached.
    """

    messages: Sequence[MessageResponse]
    total: int
    limit: int
    has_more: bool
    next_cursor: uuid.UUID | None = None


# ---------------------------------------------------------------------------
# Thread  (GET /{ticket_id}/thread)
# ---------------------------------------------------------------------------


class TicketSummary(BaseModel):
    """Minimal ticket context needed to render a chat window header."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    subject: str  # mapped from ticket.message
    status: str
    category: str | None
    priority: str | None
    created_at: datetime


class ThreadResponse(BaseModel):
    """
    'Open chat window' payload - everything the frontend needs in one call.

    Instead of two requests (GET /tickets/{id} + GET /chat/{id}/messages),
    the frontend calls GET /chat/{id}/thread and gets both.
    Pagination works identically to MessageListResponse.
    """

    ticket: TicketSummary
    messages: Sequence[MessageResponse]
    total: int
    limit: int
    has_more: bool
    next_cursor: uuid.UUID | None = None
