"""update entitites

Revision ID: 16bd54e2bbaf
Revises: 513d6860a8a7
Create Date: 2026-04-07 15:47:47.854869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bd54e2bbaf'
down_revision: Union[str, Sequence[str], None] = '513d6860a8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    op.alter_column('tickets', 'id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    op.alter_column('tickets', 'user_id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=app.infrastructure.database.GUID(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tickets', 'user_id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tickets', 'id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'target_id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'id',
               existing_type=app.infrastructure.database.GUID(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
